### ISSUE TITLE
make documentation Sphinx suitable

### ISSUE THREAD

**Issue by jfsehuanes** [bendalab/thunderfish#46]

**Comment by jfsehuanes** [comment]
Hey @fabiansinz! Could you give us a hint on how to format the docu so that it looks nice in Sphinx?
This would be awesome!

**Comment by janscience** [comment]
... but at the same time the output in IPhyton (the doc string of the functions) should be nice, like in numpy. That speaks agains :param and friends. numpy does not use :param but still gets a sphinx documentation.

**Comment by janscience** [comment]
I did some research regarding documentation styles. A good overview gives daouzli at http://stackoverflow.com/questions/3898572/what-is-the-standard-python-docstring-format
There are three main flavours:

reST: the pycharm default with ":param" and friends

Google: no keywords, very clean plain text

numpy doc: similar to google, but sphinx plugin available, see 
https://github.com/numpy/numpy/blob/master/doc/HOWTO_DOCUMENT.rst.txt

Seems like numpy doc is the best compromise between having uncorrupted doc strings that are directly readable, e.g. in ipython, and a nice spinx formatted output. Google docs are plain rest formatted doc strings, so in sphinx parameters and return values will not be highlighted in special ways. reST with :param and friends give nice sphinx output but ugly doc strings. I would opt for numpy doc!

To let pycharm create numpy doc stubs, see:
https://www.jetbrains.com/help/pycharm/2016.1/python-integrated-tools.html

For emacs see to last comment on:
http://emacs.stackexchange.com/questions/19422/library-for-automatically-inserting-python-docstring-in-google-style

**Comment by janscience** [comment]
We decided to use numpy doc style!

For details see my previous comment.

So: please **update you doc string to numpy doc style whenever you work on a module**!!!

**Comment by janscience** [comment]
Documentation is generated by pdoc3.
