### ISSUE TITLE
Write tests

### ISSUE THREAD

**Issue by fabiansinz** [bendalab/thunderfish#6]
Write unit tests to ensure everything is running smoothly. I'd use nosetest for that. I can also help you to hook that up to travis so tests are automatically run whenever a pull request is sent.

**Comment by jgrewe** [comment]
@fabiansinz would you mind to create the basic infrastructure for the unit tests?

**Comment by fabiansinz** [comment]
No problem. @jfsehuanes shall I restructure the folders or do you want to do that when writing the setup? In the latter case, I'd wait until your done. I propose the following structure

```
thunderfish/
  setup.py
  thunderfish/
     __init__.py
     ...
  tests/
  doc/
```

**Comment by jgrewe** [comment]
Test
- [ ]

**Comment by janscience** [comment]
we have tests.
