### ISSUE TITLE
Resolved: unofficial binary for PyAudio needed to install thunderfish (Win 10)

### ISSUE THREAD

**Issue by muchaste** [bendalab/thunderfish#96]
The required PyAudio lib didn't install properly via pip causing the thunderfish install to halt. This is a PyAudio issue and not a thunderfish issue but maybe this happens to others as well.
This problem is resolved by installing PyAudio from a downloaded binary file from here: https://www.lfd.uci.edu/~gohlke/pythonlibs/#pyaudio
execute pip install [download directory]

**Comment by janscience** [comment]
Thank you for noticing and suggesting a solution. I will add that link to the audioio docs.

I removed all audio packages from the requirements of audioio. This way audioio (and thus thunderfish) should install without problems now. Can you please check? When it works with the updated audioio pip packages you can close this issue.

If more features are needed libsndfile and pyaudio need to be installed manually afterwards as described in audioio docs. These docs, however, must be improved to also cover windows installs. Any suggestions are welcome!

**Comment by janscience** [comment]
Can you also please test the installation of the sounddevice package as an alternative to PyAudio?
```
pip install sounddevice
```

**Comment by muchaste** [comment]
works like a charm now, no trouble installing either thunderfish or sounddevice into a clean venv, EOD playback works well (as soon as sounddevice is installed)

**Comment by janscience** [comment]
Thank you!
